// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUSwzNZdz32l9JlHPAX1KLxhywo7aQ9No',
    appId: '1:687353752148:web:4ceda806b73784b08bdbc1',
    messagingSenderId: '687353752148',
    projectId: 'chatapp-c62ed',
    authDomain: 'chatapp-c62ed.firebaseapp.com',
    storageBucket: 'chatapp-c62ed.firebasestorage.app',
    measurementId: 'G-GVJLMSKZ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wpnmttAcmPp99WNclOJAhbuThL323gQ',
    appId: '1:687353752148:android:2610ca75d0581a978bdbc1',
    messagingSenderId: '687353752148',
    projectId: 'chatapp-c62ed',
    storageBucket: 'chatapp-c62ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxb4K_3cBPan6z9UffeENHCTZFs3AZM8',
    appId: '1:687353752148:ios:83e891b65232ec018bdbc1',
    messagingSenderId: '687353752148',
    projectId: 'chatapp-c62ed',
    storageBucket: 'chatapp-c62ed.firebasestorage.app',
    iosBundleId: 'com.example.chatappi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnxb4K_3cBPan6z9UffeENHCTZFs3AZM8',
    appId: '1:687353752148:ios:83e891b65232ec018bdbc1',
    messagingSenderId: '687353752148',
    projectId: 'chatapp-c62ed',
    storageBucket: 'chatapp-c62ed.firebasestorage.app',
    iosBundleId: 'com.example.chatappi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUSwzNZdz32l9JlHPAX1KLxhywo7aQ9No',
    appId: '1:687353752148:web:87fcff8194ea77118bdbc1',
    messagingSenderId: '687353752148',
    projectId: 'chatapp-c62ed',
    authDomain: 'chatapp-c62ed.firebaseapp.com',
    storageBucket: 'chatapp-c62ed.firebasestorage.app',
    measurementId: 'G-5PE3JCT71F',
  );

}