// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmISLeh9hdFbGgmrQ3bWOnB-qKhkzU8SA',
    appId: '1:66787575731:web:467c3ec18a3fdb56ee6dc6',
    messagingSenderId: '66787575731',
    projectId: 'chatt-8ac72',
    authDomain: 'chatt-8ac72.firebaseapp.com',
    storageBucket: 'chatt-8ac72.firebasestorage.app',
    measurementId: 'G-R7PRQ4WZMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcA2mwAPLD3f3SgRmD3lUxZclIijjAxw',
    appId: '1:66787575731:android:148448cbe9bf336cee6dc6',
    messagingSenderId: '66787575731',
    projectId: 'chatt-8ac72',
    storageBucket: 'chatt-8ac72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPlgRwsVtVwG7exLvAhiAxZ6tpkCTOwEo',
    appId: '1:66787575731:ios:f5572cf30d430952ee6dc6',
    messagingSenderId: '66787575731',
    projectId: 'chatt-8ac72',
    storageBucket: 'chatt-8ac72.firebasestorage.app',
    iosBundleId: 'com.example.chattest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPlgRwsVtVwG7exLvAhiAxZ6tpkCTOwEo',
    appId: '1:66787575731:ios:f5572cf30d430952ee6dc6',
    messagingSenderId: '66787575731',
    projectId: 'chatt-8ac72',
    storageBucket: 'chatt-8ac72.firebasestorage.app',
    iosBundleId: 'com.example.chattest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmISLeh9hdFbGgmrQ3bWOnB-qKhkzU8SA',
    appId: '1:66787575731:web:76d43b488d5edc3eee6dc6',
    messagingSenderId: '66787575731',
    projectId: 'chatt-8ac72',
    authDomain: 'chatt-8ac72.firebaseapp.com',
    storageBucket: 'chatt-8ac72.firebasestorage.app',
    measurementId: 'G-8XTG2QDE30',
  );
}
